spring:
  config:
    import: optional:file:.env
  application:
    name: api
    cache:
      type: caffeine
      cache-names: kinopoiskMovies
      caffeine:
        spec: maximumSize=1000,expireAfterWrite=24h

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_db
    username: movie_user
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

kinopoisk:
  api:
    token: ${KINOPOISK_API_TOKEN}
    url: https://kinopoiskapiunofficial.tech